# Site settings
title: The Journey to Becoming a Developer
header-img: img/home-bg.png
email: eddiemoonie@gmail.com
copyright_name: eddiemoonie
description: > # this means to ignore newlines until "baseurl:"
  One Line at a Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eddiemoonie
learn_profile: eddiemoonie
email_username: eddiemoonie@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
